logging:
  level:
    root: INFO
server:
  port: 8041

management:
  server:
    port: 8041
  endpoints:
    enabled-by-default: true
    web.exposure.include: '*'
  endpoint:
    info.enabled: true
    health:
      enabled: true
      show-details: always
    loggers.enabled: true
    prometheus.enabled: true

services:
  notification-core-service-url: http://localhost:8085/v1

#logging.level.org.springframework.web: DEBUG